// 서울시 주요 121장소 목록
// 출처: 서울 열린데이터광장 "서울시 주요 121장소 목록.xlsx" (2026.04.14 기준)
// 자동 생성 — 수동 편집 금지. 원본 파일 갱신 시 재생성할 것.

export const POI_LIST = [
  { cd: 'POI001', nm: '강남 MICE 관광특구', category: '관광특구' },
  { cd: 'POI002', nm: '동대문 관광특구', category: '관광특구' },
  { cd: 'POI003', nm: '명동 관광특구', category: '관광특구' },
  { cd: 'POI004', nm: '이태원 관광특구', category: '관광특구' },
  { cd: 'POI005', nm: '잠실 관광특구', category: '관광특구' },
  { cd: 'POI006', nm: '종로·청계 관광특구', category: '관광특구' },
  { cd: 'POI007', nm: '홍대 관광특구', category: '관광특구' },
  { cd: 'POI008', nm: '경복궁', category: '고궁·문화유산' },
  { cd: 'POI009', nm: '광화문·덕수궁', category: '고궁·문화유산' },
  { cd: 'POI010', nm: '보신각', category: '고궁·문화유산' },
  { cd: 'POI011', nm: '서울 암사동 유적', category: '고궁·문화유산' },
  { cd: 'POI012', nm: '창덕궁·종묘', category: '고궁·문화유산' },
  { cd: 'POI013', nm: '가산디지털단지역', category: '인구밀집지역' },
  { cd: 'POI014', nm: '강남역', category: '인구밀집지역' },
  { cd: 'POI015', nm: '건대입구역', category: '인구밀집지역' },
  { cd: 'POI016', nm: '고덕역', category: '인구밀집지역' },
  { cd: 'POI017', nm: '고속터미널역', category: '인구밀집지역' },
  { cd: 'POI018', nm: '교대역', category: '인구밀집지역' },
  { cd: 'POI019', nm: '구로디지털단지역', category: '인구밀집지역' },
  { cd: 'POI020', nm: '구로역', category: '인구밀집지역' },
  { cd: 'POI021', nm: '군자역', category: '인구밀집지역' },
  { cd: 'POI023', nm: '대림역', category: '인구밀집지역' },
  { cd: 'POI024', nm: '동대문역', category: '인구밀집지역' },
  { cd: 'POI025', nm: '뚝섬역', category: '인구밀집지역' },
  { cd: 'POI026', nm: '미아사거리역', category: '인구밀집지역' },
  { cd: 'POI027', nm: '발산역', category: '인구밀집지역' },
  { cd: 'POI029', nm: '사당역', category: '인구밀집지역' },
  { cd: 'POI030', nm: '삼각지역', category: '인구밀집지역' },
  { cd: 'POI031', nm: '서울대입구역', category: '인구밀집지역' },
  { cd: 'POI032', nm: '서울식물원·마곡나루역', category: '인구밀집지역' },
  { cd: 'POI033', nm: '서울역', category: '인구밀집지역' },
  { cd: 'POI034', nm: '선릉역', category: '인구밀집지역' },
  { cd: 'POI035', nm: '성신여대입구역', category: '인구밀집지역' },
  { cd: 'POI036', nm: '수유역', category: '인구밀집지역' },
  { cd: 'POI037', nm: '신논현역·논현역', category: '인구밀집지역' },
  { cd: 'POI038', nm: '신도림역', category: '인구밀집지역' },
  { cd: 'POI039', nm: '신림역', category: '인구밀집지역' },
  { cd: 'POI040', nm: '신촌·이대역', category: '인구밀집지역' },
  { cd: 'POI041', nm: '양재역', category: '인구밀집지역' },
  { cd: 'POI042', nm: '역삼역', category: '인구밀집지역' },
  { cd: 'POI043', nm: '연신내역', category: '인구밀집지역' },
  { cd: 'POI044', nm: '오목교역·목동운동장', category: '인구밀집지역' },
  { cd: 'POI045', nm: '왕십리역', category: '인구밀집지역' },
  { cd: 'POI046', nm: '용산역', category: '인구밀집지역' },
  { cd: 'POI047', nm: '이태원역', category: '인구밀집지역' },
  { cd: 'POI048', nm: '장지역', category: '인구밀집지역' },
  { cd: 'POI049', nm: '장한평역', category: '인구밀집지역' },
  { cd: 'POI050', nm: '천호역', category: '인구밀집지역' },
  { cd: 'POI051', nm: '총신대입구(이수)역', category: '인구밀집지역' },
  { cd: 'POI052', nm: '충정로역', category: '인구밀집지역' },
  { cd: 'POI053', nm: '합정역', category: '인구밀집지역' },
  { cd: 'POI054', nm: '혜화역', category: '인구밀집지역' },
  { cd: 'POI055', nm: '홍대입구역(2호선)', category: '인구밀집지역' },
  { cd: 'POI056', nm: '회기역', category: '인구밀집지역' },
  { cd: 'POI058', nm: '가락시장', category: '발달상권' },
  { cd: 'POI059', nm: '가로수길', category: '발달상권' },
  { cd: 'POI060', nm: '광장(전통)시장', category: '발달상권' },
  { cd: 'POI061', nm: '김포공항', category: '발달상권' },
  { cd: 'POI063', nm: '노량진', category: '발달상권' },
  { cd: 'POI064', nm: '덕수궁길·정동길', category: '발달상권' },
  { cd: 'POI066', nm: '북촌한옥마을', category: '발달상권' },
  { cd: 'POI067', nm: '서촌', category: '발달상권' },
  { cd: 'POI068', nm: '성수카페거리', category: '발달상권' },
  { cd: 'POI070', nm: '쌍문역', category: '인구밀집지역' },
  { cd: 'POI071', nm: '압구정로데오거리', category: '발달상권' },
  { cd: 'POI072', nm: '여의도', category: '발달상권' },
  { cd: 'POI073', nm: '연남동', category: '발달상권' },
  { cd: 'POI074', nm: '영등포 타임스퀘어', category: '발달상권' },
  { cd: 'POI076', nm: '용리단길', category: '발달상권' },
  { cd: 'POI077', nm: '이태원 앤틱가구거리', category: '발달상권' },
  { cd: 'POI078', nm: '인사동', category: '발달상권' },
  { cd: 'POI079', nm: '창동 신경제 중심지', category: '발달상권' },
  { cd: 'POI080', nm: '청담동 명품거리', category: '발달상권' },
  { cd: 'POI081', nm: '청량리 제기동 일대 전통시장', category: '발달상권' },
  { cd: 'POI082', nm: '해방촌·경리단길', category: '발달상권' },
  { cd: 'POI083', nm: 'DDP(동대문디자인플라자)', category: '발달상권' },
  { cd: 'POI084', nm: 'DMC(디지털미디어시티)', category: '발달상권' },
  { cd: 'POI085', nm: '강서한강공원', category: '공원' },
  { cd: 'POI086', nm: '고척돔', category: '공원' },
  { cd: 'POI087', nm: '광나루한강공원', category: '공원' },
  { cd: 'POI088', nm: '광화문광장', category: '공원' },
  { cd: 'POI089', nm: '국립중앙박물관·용산가족공원', category: '공원' },
  { cd: 'POI090', nm: '난지한강공원', category: '공원' },
  { cd: 'POI091', nm: '남산공원', category: '공원' },
  { cd: 'POI092', nm: '노들섬', category: '공원' },
  { cd: 'POI093', nm: '뚝섬한강공원', category: '공원' },
  { cd: 'POI094', nm: '망원한강공원', category: '공원' },
  { cd: 'POI095', nm: '반포한강공원', category: '공원' },
  { cd: 'POI096', nm: '북서울꿈의숲', category: '공원' },
  { cd: 'POI098', nm: '서리풀공원·몽마르뜨공원', category: '공원' },
  { cd: 'POI100', nm: '서울대공원', category: '공원' },
  { cd: 'POI101', nm: '서울숲공원', category: '공원' },
  { cd: 'POI102', nm: '아차산', category: '공원' },
  { cd: 'POI103', nm: '양화한강공원', category: '공원' },
  { cd: 'POI104', nm: '어린이대공원', category: '공원' },
  { cd: 'POI105', nm: '여의도한강공원', category: '공원' },
  { cd: 'POI106', nm: '월드컵공원', category: '공원' },
  { cd: 'POI107', nm: '응봉산', category: '공원' },
  { cd: 'POI108', nm: '이촌한강공원', category: '공원' },
  { cd: 'POI109', nm: '잠실종합운동장', category: '공원' },
  { cd: 'POI110', nm: '잠실한강공원', category: '공원' },
  { cd: 'POI111', nm: '잠원한강공원', category: '공원' },
  { cd: 'POI112', nm: '청계산', category: '공원' },
  { cd: 'POI114', nm: '북창동 먹자골목', category: '발달상권' },
  { cd: 'POI115', nm: '남대문시장', category: '발달상권' },
  { cd: 'POI116', nm: '익선동', category: '발달상권' },
  { cd: 'POI117', nm: '신정네거리역', category: '인구밀집지역' },
  { cd: 'POI118', nm: '잠실새내역', category: '인구밀집지역' },
  { cd: 'POI119', nm: '잠실역', category: '인구밀집지역' },
  { cd: 'POI120', nm: '잠실롯데타워·석촌호수', category: '발달상권' },
  { cd: 'POI121', nm: '송리단길·호수단길', category: '발달상권' },
  { cd: 'POI122', nm: '신촌 스타광장', category: '발달상권' },
  { cd: 'POI123', nm: '보라매공원', category: '공원' },
  { cd: 'POI124', nm: '서대문독립공원', category: '공원' },
  { cd: 'POI125', nm: '안양천', category: '공원' },
  { cd: 'POI126', nm: '여의서로', category: '공원' },
  { cd: 'POI127', nm: '올림픽공원', category: '공원' },
  { cd: 'POI128', nm: '홍제폭포', category: '공원' },
  { cd: 'POI129', nm: '송현녹지광장', category: '공원' },
  { cd: 'POI130', nm: '시의회 앞', category: '인구밀집지역' },
  { cd: 'POI131', nm: '숭례문', category: '인구밀집지역' },
];

// 통합 API(citydata) raw 수집 대상 — 용량 문제로 소수만 지정
export const RAW_TARGETS = [
  'POI009', // 광화문·덕수궁 — 오피스 / 실측 검증 기준점
  'POI007', // 홍대 관광특구 — 야간·주말형
  'POI014', // 강남역 — 교통요지·최대 유동
  'POI003', // 명동 관광특구 — 외국인 관광
  'POI072', // 여의도 — 오피스 + 이벤트
];

export const CONFIG = {
  API_BASE: 'http://openapi.seoul.go.kr:8088',
  SERVICE_PPLTN: 'citydata_ppltn',
  SERVICE_CITYDATA: 'citydata', // 미검증 — 실패 시 OA-21285 페이지에서 확인 후 DEVIATIONS.md 기록
  REQUEST_DELAY_MS: 200,
  MAX_RETRY: 2,
  RETRY_DELAY_MS: 5000,
  RUN_TIMEOUT_MS: 8 * 60 * 1000,
  FORECAST_SAVE_MINUTE_MAX: 9, // ppltn_time 분이 0~9일 때만 예측 저장
};
